name: Build

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        qt: [6.11.1]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt }}
          setup-python: false
          aqtsource: git+https://github.com/miurahr/aqtinstall@master
        env:
          PIP_BREAK_SYSTEM_PACKAGES: "1"

      - name: Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON

      - name: Build
        run: cmake --build build --parallel

      - name: Test
        working-directory: build
        env:
          QT_QPA_PLATFORM: offscreen
        run: ctest --output-on-failure --parallel -C Release
